### ISSUE TITLE
Unit tests not running

### ISSUE THREAD

**Issue by bingomanatee** [posquit0/koa-rest-api-boilerplate#9]
I am creating unit tests in my code and they are not being detected; see attached screenshot
<img width="1126" alt="screen shot 2018-06-03 at 10 13 32 am" src="https://user-images.githubusercontent.com/684016/40889194-8e318cf0-6717-11e8-8094-2a72363b2a8f.png">

**Comment by posquit0** [comment]
In this boilerplate project, unit tests are located in `test/unit` directory. If you want to use `.spec.js` in source code directory, you should change the command in `package.json`.
